import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { AlertTriangle, ArrowRight, CheckCircle2, Filter, MessageSquareReply, ShieldAlert, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import { CX_ISSUES, type CXIssue, type CXSeverity, type CXStatus, type LoopStatus } from '@/data/customer-experience';
import { useCXM } from '@/store/CXMContext';
import { customerPhaseForLegacyId } from '@/lib/journey-taxonomy';
import { cn } from '@/lib/utils';

const SEVERITY_STYLE: Record<CXSeverity, string> = { critical: 'border-rose-200 bg-rose-50 text-rose-700', high: 'border-amber-200 bg-amber-50 text-amber-700', medium: 'border-sky-200 bg-sky-50 text-sky-700' };
const STATUS_LABEL: Record<CXStatus, string> = { detecting: 'Mới phát hiện', investigating: 'Điều tra', fixing: 'Đang sửa', resolved: 'Đã xác nhận' };
const LOOP_STYLE: Record<LoopStatus, string> = { 'Chưa phản hồi': 'text-rose-700', 'Chờ bản sửa': 'text-amber-700', 'Sẵn sàng liên hệ': 'text-sky-700', 'Đã khép vòng': 'text-emerald-700' };
const CONTROL_TOWER_IDS = new Set(['CXI-021', 'CXI-017', 'CXI-013']);

export default function IssueHub() {
  const { selectedCustomerPhaseId } = useCXM();
  const [params] = useSearchParams();
  const [theme, setTheme] = useState('Tất cả chủ đề');
  const requestedIssueId = params.get('issue');
  const [selectedId, setSelectedId] = useState(requestedIssueId ?? 'CXI-024');
  const issues = useMemo(() => CX_ISSUES.filter((issue) => issue.id === requestedIssueId || ((theme === 'Tất cả chủ đề' || issue.theme === theme) && (selectedCustomerPhaseId === 'all' || customerPhaseForLegacyId(issue.phaseId).id === selectedCustomerPhaseId))).sort((a, b) => b.priorityScore - a.priorityScore), [theme, selectedCustomerPhaseId, requestedIssueId]);
  const selected = issues.find((issue) => issue.id === selectedId) ?? issues[0] ?? null;
  const scoped = CX_ISSUES.filter((issue) => selectedCustomerPhaseId === 'all' || customerPhaseForLegacyId(issue.phaseId).id === selectedCustomerPhaseId);
  const repeatContacts = scoped.reduce((sum, issue) => sum + Math.round(issue.contacts * issue.repeatContactRate / 100), 0);
  const churnRisk = scoped.reduce((sum, issue) => sum + issue.churnRiskCustomers, 0);
  const pendingLoop = scoped.filter((issue) => issue.loopStatus !== 'Đã khép vòng').reduce((sum, issue) => sum + issue.customersToContact, 0);

  return <div className="flex min-h-full min-w-[1100px] flex-col bg-slate-50/50">
    <header className="border-b border-border bg-white px-6 py-5"><div className="flex items-start justify-between gap-8"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Customer Experience</p><h1 className="mt-1 text-2xl font-bold tracking-tight">CX Issue Register</h1><p className="mt-1 text-xs text-muted-foreground">Hồ sơ tất cả điểm gãy từ VOC, hành vi và vận hành; Control Tower chỉ lấy các issue cần điều hành.</p></div><div className="flex gap-2"><Link to="/" className="inline-flex h-9 items-center gap-2 rounded-lg border border-primary/20 bg-white px-3 text-xs font-semibold text-primary">Mở CX Control Tower <ArrowRight className="h-3.5 w-3.5" /></Link><Link to="/board" className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground">Mở Action Register <ArrowRight className="h-3.5 w-3.5" /></Link></div></div>
      <div className="mt-5 flex h-11 max-w-3xl items-center gap-3 rounded-xl border border-primary/25 bg-primary/[0.03] px-4 shadow-sm"><Sparkles className="h-4 w-4 text-primary" /><span className="text-xs font-medium">Điểm gãy nào đang tạo repeat contact và churn risk cao nhất?</span><span className="ml-auto rounded-md bg-white px-2 py-1 text-[9px] text-muted-foreground">Impact-ranked</span></div>
    </header>

    <section className="grid grid-cols-[minmax(0,1.4fr)_repeat(3,minmax(150px,0.55fr))] border-b border-border bg-white"><div className="border-r border-border p-5"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-rose-700"><ShieldAlert className="h-3.5 w-3.5" />CX warning</div><p className="mt-2 text-sm font-semibold leading-5">Nạp tiền treo là ưu tiên đầu tiên: vừa có severity cao, repeat contact 38% và 46 khách có tín hiệu churn.</p><p className="mt-1 text-[10px] text-muted-foreground">Không ưu tiên chỉ theo số ticket; đã tính customer value và business impact.</p></div><Summary label="Repeat contacts" value={String(repeatContacts)} note="Liên hệ từ lần hai" tone="warning" /><Summary label="Churn-risk exposed" value={String(churnRisk)} note="Khách cần can thiệp" tone="risk" /><Summary label="Chờ close-loop" value={String(pendingLoop)} note="Khách cần phản hồi" /></section>

    <div className="flex items-center gap-2 border-b border-border bg-white px-5 py-3"><Filter className="h-3.5 w-3.5 text-muted-foreground" /><select value={theme} onChange={(event) => setTheme(event.target.value)} aria-label="Lọc chủ đề CX" className="h-8 rounded-md border border-input bg-white px-2.5 text-xs outline-none"><option>Tất cả chủ đề</option>{[...new Set(CX_ISSUES.map((issue) => issue.theme))].map((item) => <option key={item}>{item}</option>)}</select><span className="ml-auto text-[10px] text-muted-foreground">Xếp theo CX impact score · {issues.length} issues</span></div>

    <div className="grid min-h-[590px] flex-1 grid-cols-[minmax(620px,1fr)_410px]">
      <main className="border-r border-border bg-slate-50/60"><div className="grid grid-cols-[minmax(230px,1.3fr)_105px_120px_105px_105px] gap-3 border-b border-border bg-white px-4 py-3 text-[9px] font-semibold uppercase tracking-wider text-muted-foreground"><span>Issue / journey friction</span><span>Repeat</span><span>CX impact</span><span>Risk</span><span>Resolution</span></div><div className="divide-y divide-border">{issues.map((issue) => <IssueRow key={issue.id} issue={issue} active={selected?.id === issue.id} onSelect={() => setSelectedId(issue.id)} />)}{issues.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">Không có issue phù hợp.</div>}</div></main>
      <IssueDetail issue={selected} />
    </div>
  </div>;
}

function IssueRow({ issue, active, onSelect }: { issue: CXIssue; active: boolean; onSelect: () => void }) {
  const TrendIcon = issue.trend >= 0 ? TrendingUp : TrendingDown;
  return <button type="button" onClick={onSelect} aria-pressed={active} className={cn('grid w-full grid-cols-[minmax(230px,1.3fr)_105px_120px_105px_105px] items-center gap-3 bg-white px-4 py-4 text-left transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring', active && 'bg-primary/5 shadow-[inset_3px_0_0_hsl(var(--primary))]')}><span className="min-w-0"><span className="flex items-center gap-2"><span className="font-mono text-[9px] text-muted-foreground">{issue.id}</span><span className={cn('rounded-full border px-1.5 py-0.5 text-[8px] font-semibold', SEVERITY_STYLE[issue.severity])}>{issue.severity}</span>{CONTROL_TOWER_IDS.has(issue.id) && <span className="rounded-full bg-primary/10 px-1.5 py-0.5 text-[8px] font-semibold text-primary">Trong Control Tower</span>}</span><span className="mt-1 block text-[11px] font-semibold">{issue.title}</span><span className="mt-1 block truncate text-[9px] text-muted-foreground">{customerPhaseForLegacyId(issue.phaseId).name} · {issue.touchpoint}</span></span><span><strong className="block text-sm tabular-nums">{issue.repeatContactRate}%</strong><span className="mt-1 block text-[9px] text-muted-foreground">{issue.contacts} contacts</span></span><span><strong className="block text-sm tabular-nums">{issue.priorityScore}</strong><span className={cn('mt-1 flex items-center gap-1 text-[9px]', issue.trend >= 0 ? 'text-rose-700' : 'text-emerald-700')}><TrendIcon className="h-3 w-3" />{Math.abs(issue.trend)}%</span></span><span><strong className="block text-sm tabular-nums text-rose-700">{issue.churnRiskCustomers}</strong><span className="mt-1 block text-[9px] text-muted-foreground">{issue.highValueCustomers} high-value</span></span><span><span className="block text-[10px] font-medium">{STATUS_LABEL[issue.status]}</span><span className={cn('mt-1 block text-[9px] font-medium', LOOP_STYLE[issue.loopStatus])}>{issue.loopStatus}</span></span></button>;
}

function IssueDetail({ issue }: { issue: CXIssue | null }) {
  if (!issue) return <aside className="flex items-center justify-center bg-white text-sm text-muted-foreground">Chọn issue để xem chi tiết.</aside>;
  return <aside className="bg-white"><div className="border-b border-border p-5"><div className="flex items-center justify-between"><span className={cn('rounded-full border px-2 py-0.5 text-[9px] font-semibold', SEVERITY_STYLE[issue.severity])}>{issue.severity}</span><span className="font-mono text-[9px] text-muted-foreground">{issue.id} · {issue.updated}</span></div><h2 className="mt-3 text-base font-bold leading-6">{issue.title}</h2><p className="mt-1 text-[10px] text-muted-foreground">{issue.theme} · {issue.touchpointId}</p></div><div className="space-y-5 p-5">
    <section><Heading>Root cause hypothesis</Heading><p className="text-[11px] font-medium leading-5 text-slate-800">{issue.rootCause}</p><p className="mt-2 rounded-lg bg-slate-50 p-3 text-[10px] leading-4 text-muted-foreground">{issue.signal}</p></section>
    <section><Heading>Customer & business impact</Heading><div className="grid grid-cols-4 gap-2"><Fact label="Affected" value={String(issue.affectedCustomers)} /><Fact label="Repeat" value={`${issue.repeatContactRate}%`} tone="text-rose-700" /><Fact label="CSAT" value={`${issue.csatImpact}pt`} tone="text-rose-700" /><Fact label="Churn risk" value={String(issue.churnRiskCustomers)} tone="text-rose-700" /></div></section>
    <section><Heading>Customer evidence</Heading><div className="space-y-2">{issue.evidence.map((item) => <blockquote key={item.quote} className="rounded-lg border border-border bg-slate-50 p-3"><p className="text-[10px] leading-4 text-slate-700">“{item.quote}”</p><footer className="mt-2 flex justify-between text-[9px] text-muted-foreground"><span>{item.channel}</span><span>{item.time}</span></footer></blockquote>)}</div></section>
    <section className="rounded-xl border border-primary/20 bg-primary/[0.04] p-4"><div className="flex items-center gap-2 text-[10px] font-semibold text-primary"><AlertTriangle className="h-3.5 w-3.5" />Resolution plan</div><p className="mt-2 text-[11px] font-medium leading-5">{issue.resolution}</p><div className="mt-3 flex items-center justify-between border-t border-primary/10 pt-3 text-[9px]"><span className="text-muted-foreground">Action / owner</span><span className="font-semibold text-foreground">{issue.actionId} · {issue.owner}</span></div>{CONTROL_TOWER_IDS.has(issue.id) && <><p className="mt-3 text-[9px] leading-4 text-muted-foreground">Được đưa vào Control Tower vì có journey impact, evidence đủ tin cậy và cần quyết định liên phòng ban.</p><Link to={`/?issue=${issue.id}`} className="mt-2 inline-flex items-center gap-1 text-[10px] font-semibold text-primary hover:underline">Mở đúng issue trong Control Tower <ArrowRight className="h-3 w-3" /></Link></>}</section>
    <section><Heading>Close the loop</Heading><div className="rounded-lg border border-border p-3"><div className="flex items-center gap-2"><MessageSquareReply className="h-4 w-4 text-primary" /><span className={cn('text-[10px] font-semibold', LOOP_STYLE[issue.loopStatus])}>{issue.loopStatus}</span><span className="ml-auto text-[9px] text-muted-foreground">{issue.customersToContact} khách cần liên hệ</span></div>{issue.outcome ? <p className="mt-2 flex gap-2 text-[10px] leading-4 text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5 shrink-0" />{issue.outcome}</p> : <p className="mt-2 text-[10px] leading-4 text-muted-foreground">Khi action được xác nhận hoàn tất, tạo danh sách khách bị ảnh hưởng, gửi cập nhật và đo sentiment/CSAT sau xử lý.</p>}</div></section>
  </div></aside>;
}

function Summary({ label, value, note, tone }: { label: string; value: string; note: string; tone?: 'warning' | 'risk' }) { return <div className="border-r border-border p-5 last:border-r-0"><p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className={cn('mt-2 text-2xl font-bold tabular-nums', tone === 'warning' ? 'text-amber-700' : tone === 'risk' ? 'text-rose-700' : 'text-foreground')}>{value}</p><p className="mt-1 text-[9px] text-muted-foreground">{note}</p></div>; }
function Heading({ children }: { children: string }) { return <h3 className="mb-2 text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">{children}</h3>; }
function Fact({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="rounded-lg bg-slate-50 p-2.5"><p className="text-[8px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={cn('mt-1 text-sm font-bold', tone)}>{value}</p></div>; }
